### PyTorch Fundamentals

In [2]:
## Import Pytorch and check it's version
import torch
print(f"The Current PyTorch version is :{torch.__version__}")

The Current PyTorch version is :2.11.0+cpu


#### 1. Creating Tensors

In [3]:
## 1.1 Scalar ( a single number)
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# let's print more about it
print(f"Scalar : {scalar}")
print(f"Dimension : {scalar.ndim}")
print(f"Shape : {scalar.shape}")
print(f"Device on which scalar is running : {scalar.device}")

Scalar : 7
Dimension : 0
Shape : torch.Size([])
Device on which scalar is running : cpu


In [5]:
# 1.2 Vector (a 1-D array of numbers)
vector = torch.tensor([1,2,3])

In [6]:
print(f"Vector : {vector}")
print(f"Dimension : {vector.ndim}")
print(f"Shape : {vector.shape}")  # (n,) n is number of elements
print(f"Device on which vector is running : {vector.device}")

Vector : tensor([1, 2, 3])
Dimension : 1
Shape : torch.Size([3])
Device on which vector is running : cpu


In [7]:
# 1.3 Matrix (a 2-D array of numbers)
MATRIX = torch.tensor([[1, 2 ,3],
                       [5, 6 , 7]
])

In [8]:
print(f"Matrix : {MATRIX}")
print(f"Dimension : {MATRIX.ndim}")
print(f"Shape : {MATRIX.shape}")  # (rows , columns)

Matrix : tensor([[1, 2, 3],
        [5, 6, 7]])
Dimension : 2
Shape : torch.Size([2, 3])


In [9]:
# 1.4 Tensor (a generalization of all to n dimensions)
TENSOR= torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

In [10]:
print(f"Tensor : {TENSOR}")
print(f"Dimension : {TENSOR.ndim}")
print(f"Shape : {TENSOR.shape}")

Tensor : tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Dimension : 3
Shape : torch.Size([2, 2, 2])


Things to remember:

A Tensor is a `genralization` of scalar , vector and matrix to `n` dimensions

* A Tensor of `0` dimension is a `Scalar`.
* A Tensor of `1` dimension is a `Vector`.
* A Tensor of `2` dimension is a `Matrix`.

Generally we called Tensor to a Tensor have more than `2` dimension.

Note:

* *`torch.Size` (or .shape) tells you how many elements exist along each dimension of a tensor.*
* For a tensor with shape [d0, d1, d2, ..., dn]:

     Number of values in the shape = number of dimensions of the tensor.

     Each value = size (length) of that specific dimension.
     
* Total number of elements = product of all shape values


In [11]:
# 1.5 Zero Tensor (having 0's as an  element)
zero_tensor = torch.zeros(size = (2,2))
print(f"Tensor : {zero_tensor}")
print(f"Dimension : {zero_tensor.ndim}")
print(f"Shape : {zero_tensor.shape}")

Tensor : tensor([[0., 0.],
        [0., 0.]])
Dimension : 2
Shape : torch.Size([2, 2])


In [12]:
# 1.6 Ones Tensor (having 1's as an element)
ones_tensor = torch.ones(size = (3,3))
print(f"Tensor : {ones_tensor}")
print(f"Dimension : {ones_tensor.ndim}")
print(f"Shape : {ones_tensor.shape}")

Tensor : tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
Dimension : 2
Shape : torch.Size([3, 3])


In [13]:
# 1.7 Range Tensor
range_tensor = torch.arange(start = 1.5,
                            step = 1,
                            end = 10.98)
range_tensor

tensor([ 1.5000,  2.5000,  3.5000,  4.5000,  5.5000,  6.5000,  7.5000,  8.5000,
         9.5000, 10.5000])

Note: In Python, you can use `range()` to create a range. However in PyTorch, `torch.range()` is deprecated and may show an error in the future.

In [14]:
# 1.8 Random tensor
random_tensor = torch.rand(size = (2,3))
random_tensor

tensor([[0.7617, 0.5644, 0.4640],
        [0.8376, 0.6512, 0.9187]])

`torch.rand()` Returns a tensor filled with random numbers from a uniform distribution on the interval [0,1).

The shape of the tensor is defined by the variable argument `size`.

Note:

In PyTorch, both `torch.rand()` and `torch.randn()` generate random tensors, but they differ in the distribution of the generated values.

`torch.rand()` Generates numbers uniformly between 0 and 1

`torch.randn()` Generates numbers from a standard normal distribution (mean = 0, std = 1).

In [15]:
random = torch.randn(size = (2,3))
random

tensor([[-0.1561, -0.1601, -1.0023],
        [ 0.4899,  0.7382, -0.9879]])

In [16]:
# Let's check it's mean and standard deviation (it will be nearly 0 and 1 not exact!)
mean = random.mean()
std = random.std()

print(f"Mean is {mean}")
print(f"Standard deviation is {std}")

Mean is -0.17973019182682037
Standard deviation is 0.7241030931472778


#### 2. Getting information from tensors


We've seen these before but three of the most common attributes you'll want to find out about tensors are:

`shape` - what shape is the tensor? (some operations require specific shape rules)

`dtype` - what datatype are the elements within the tensor stored in?

`device` - what device is the tensor stored on? (usually GPU or CPU)

In [17]:
# create a tensor
some_tensor = torch.rand(3,4)

In [20]:
# Find out details about is
print(some_tensor)
print(f"Shape is :  {some_tensor.shape}")
print(f"Datatype of tensor is : {some_tensor.dtype}")
print(f"Device tensor is stored on : {some_tensor.device}")

tensor([[0.2697, 0.2567, 0.2212, 0.9908],
        [0.5478, 0.8341, 0.8401, 0.8940],
        [0.8426, 0.2938, 0.2417, 0.7985]])
Shape is :  torch.Size([3, 4])
Datatype of tensor is : torch.float32
Device tensor is stored on : cpu


#### 3. Manipulating tensors (tensor operations)

* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [21]:
## Create two tensors
x = torch.tensor([1,2,3])
y = torch.tensor([1,1,1])

In [ ]:
# Addition of two tensors
print(x+y) # method 1
print(torch.add(x,y)) # method 2

tensor([2, 3, 4])
tensor([2, 3, 4])


In [28]:
## Subtraction
print(x-y)
print(torch.sub(x,y))
print(torch.subtract(x,y))   # alias of torch.sub

tensor([0, 1, 2])
tensor([0, 1, 2])
tensor([0, 1, 2])


In [27]:
## Multiplication (element wise)
print(x*y)
print(torch.mul(x,y))
print(torch.multiply(x,y))

tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [29]:
## Division
print(x/y)
print(torch.div(x,y))
print(torch.divide(x,y))

tensor([1., 2., 3.])
tensor([1., 2., 3.])
tensor([1., 2., 3.])


##### Matrix Multiplication (backbone of deep learning!)

One of the most common operations in machine learning and deep learning algorithms (like neural networks) is matrix multiplication.

PyTorch implements matrix multiplication functionality in the `torch.matmul()` method.


The main two rules for matrix multiplication to remember are:

1. The inner dimensions must match:

* (3, 2) @ (3, 2) won't work

* (2, 3) @ (3, 2) will work

* (3, 2) @ (2, 3) will work

2. The resulting matrix has the shape of the outer dimensions:

* (2, 3) @ (3, 2) -> (2, 2)

* (3, 2) @ (2, 3) -> (3, 3)

Note: "@" in Python is the symbol for matrix multiplication.

In [30]:
# Create tensors
X = torch.randn(size = (2,3))
Y = torch.randn(size = (3,4))

X.shape , Y.shape

(torch.Size([2, 3]), torch.Size([3, 4]))

Both the matrices are compatible for matrix multiplication as their inner dimensions are same

In [32]:
print(torch.matmul(X,Y))
print(torch.matmul(X,Y).shape)


tensor([[ 0.2145, -0.4987,  1.1391,  1.5703],
        [ 0.4754, -1.9868,  1.1616,  2.7909]])
torch.Size([2, 4])


##### One of the most common errors in deep learning (shape errors)

Because much of deep learning is multiplying and performing operations on matrices and matrices have a strict rule about what shapes and sizes can be combined, one of the most common errors you'll run into in deep learning is shape mismatches.

In [33]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

We can make matrix multiplication work between tensor_A and tensor_B by making their inner dimensions match.

One of the ways to do this is with a transpose (switch the dimensions of a given tensor).

You can perform transposes in PyTorch using either:

`torch.transpose(input, dim0, dim1)` - where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.

`tensor.T` - where tensor is the desired tensor to transpose.

In [34]:
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [35]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])
