### PyTorch Fundamentals

In [1]:
## Import Pytorch and check it's version
import torch
print(f"The Current PyTorch version is :{torch.__version__}")

The Current PyTorch version is :2.11.0+cpu


#### 1. Creating Tensors

In [2]:
## 1.1 Scalar ( a single number)
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# let's print more about it
print(f"Scalar : {scalar}")
print(f"Dimension : {scalar.ndim}")
print(f"Shape : {scalar.shape}")
print(f"Device on which scalar is running : {scalar.device}")

Scalar : 7
Dimension : 0
Shape : torch.Size([])
Device on which scalar is running : cpu


In [4]:
# 1.2 Vector (a 1-D array of numbers)
vector = torch.tensor([1,2,3])

In [5]:
print(f"Vector : {vector}")
print(f"Dimension : {vector.ndim}")
print(f"Shape : {vector.shape}")  # (n,) n is number of elements
print(f"Device on which vector is running : {vector.device}")

Vector : tensor([1, 2, 3])
Dimension : 1
Shape : torch.Size([3])
Device on which vector is running : cpu


In [6]:
# 1.3 Matrix (a 2-D array of numbers)
MATRIX = torch.tensor([[1, 2 ,3],
                       [5, 6 , 7]
])

In [7]:
print(f"Matrix : {MATRIX}")
print(f"Dimension : {MATRIX.ndim}")
print(f"Shape : {MATRIX.shape}")  # (rows , columns)

Matrix : tensor([[1, 2, 3],
        [5, 6, 7]])
Dimension : 2
Shape : torch.Size([2, 3])


In [8]:
# 1.4 Tensor (a generalization of all to n dimensions)
TENSOR= torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

In [9]:
print(f"Tensor : {TENSOR}")
print(f"Dimension : {TENSOR.ndim}")
print(f"Shape : {TENSOR.shape}")

Tensor : tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Dimension : 3
Shape : torch.Size([2, 2, 2])


Things to remember:

A Tensor is a `genralization` of scalar , vector and matrix to `n` dimensions

* A Tensor of `0` dimension is a `Scalar`.
* A Tensor of `1` dimension is a `Vector`.
* A Tensor of `2` dimension is a `Matrix`.

Generally we called Tensor to a Tensor have more than `2` dimension.

Note:

* *`torch.Size` (or .shape) tells you how many elements exist along each dimension of a tensor.*
* For a tensor with shape [d0, d1, d2, ..., dn]:

     Number of values in the shape = number of dimensions of the tensor.

     Each value = size (length) of that specific dimension.
     
* Total number of elements = product of all shape values


In [10]:
# 1.5 Zero Tensor (having 0's as an  element)
zero_tensor = torch.zeros(size = (2,2))
print(f"Tensor : {zero_tensor}")
print(f"Dimension : {zero_tensor.ndim}")
print(f"Shape : {zero_tensor.shape}")

Tensor : tensor([[0., 0.],
        [0., 0.]])
Dimension : 2
Shape : torch.Size([2, 2])


In [11]:
# 1.6 Ones Tensor (having 1's as an element)
ones_tensor = torch.ones(size = (3,3))
print(f"Tensor : {ones_tensor}")
print(f"Dimension : {ones_tensor.ndim}")
print(f"Shape : {ones_tensor.shape}")

Tensor : tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
Dimension : 2
Shape : torch.Size([3, 3])


In [12]:
# 1.7 Range Tensor
range_tensor = torch.arange(start = 1.5,
                            step = 1,
                            end = 10.98)
range_tensor

tensor([ 1.5000,  2.5000,  3.5000,  4.5000,  5.5000,  6.5000,  7.5000,  8.5000,
         9.5000, 10.5000])

Note: In Python, you can use `range()` to create a range. However in PyTorch, `torch.range()` is deprecated and may show an error in the future.

In [13]:
# 1.8 Random tensor
random_tensor = torch.rand(size = (2,3))
random_tensor

tensor([[0.8196, 0.7315, 0.8678],
        [0.2246, 0.7636, 0.8852]])

`torch.rand()` Returns a tensor filled with random numbers from a uniform distribution on the interval [0,1).

The shape of the tensor is defined by the variable argument `size`.

Note:

In PyTorch, both `torch.rand()` and `torch.randn()` generate random tensors, but they differ in the distribution of the generated values.

`torch.rand()` Generates numbers uniformly between 0 and 1

`torch.randn()` Generates numbers from a standard normal distribution (mean = 0, std = 1).

In [ ]:
random = torch.randn(size = (2,3))
random

tensor([[ 2.2207, -2.2977,  1.0995],
        [-0.8426,  1.0526,  1.2215]])

In [15]:
# Let's check it's mean and standard deviation (it will be nearly 0 and 1 not exact!)
mean = random.mean()
std = random.std()

print(f"Mean is {mean}")
print(f"Standard deviation is {std}")

Mean is 0.40900006890296936
Standard deviation is 1.6568799018859863


#### 2. Getting information from tensors


We've seen these before but three of the most common attributes you'll want to find out about tensors are:

`shape` - what shape is the tensor? (some operations require specific shape rules)

`dtype` - what datatype are the elements within the tensor stored in?

`device` - what device is the tensor stored on? (usually GPU or CPU)

In [ ]:
# create a tensor
some_tensor = torch.rand(3,4)

In [17]:
# Find out details about is
print(some_tensor)
print(f"Shape is :  {some_tensor.shape}")
print(f"Datatype of tensor is : {some_tensor.dtype}")
print(f"Device tensor is stored on : {some_tensor.device}")

tensor([[0.6176, 0.1567, 0.7212, 0.0264],
        [0.1799, 0.9993, 0.5679, 0.7770],
        [0.1814, 0.1999, 0.1861, 0.8932]])
Shape is :  torch.Size([3, 4])
Datatype of tensor is : torch.float32
Device tensor is stored on : cpu


#### 3. Manipulating tensors (tensor operations)

* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
## Create two tensors
x = torch.tensor([1,2,3])
y = torch.tensor([1,1,1])

In [ ]:
# Addition of two tensors
print(x+y) # method 1
print(torch.add(x,y)) # method 2

tensor([2, 3, 4])
tensor([2, 3, 4])


In [20]:
## Subtraction
print(x-y)
print(torch.sub(x,y))
print(torch.subtract(x,y))   # alias of torch.sub

tensor([0, 1, 2])
tensor([0, 1, 2])
tensor([0, 1, 2])


In [21]:
## Multiplication (element wise)
print(x*y)
print(torch.mul(x,y))
print(torch.multiply(x,y))

tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [ ]:
## Division
print(x/y)
print(torch.div(x,y))
print(torch.divide(x,y))

tensor([1., 2., 3.])
tensor([1., 2., 3.])
tensor([1., 2., 3.])


##### Matrix Multiplication (backbone of deep learning!)

One of the most common operations in machine learning and deep learning algorithms (like neural networks) is matrix multiplication.

PyTorch implements matrix multiplication functionality in the `torch.matmul()` method.


The main two rules for matrix multiplication to remember are:

1. The inner dimensions must match:

* (3, 2) @ (3, 2) won't work

* (2, 3) @ (3, 2) will work

* (3, 2) @ (2, 3) will work

2. The resulting matrix has the shape of the outer dimensions:

* (2, 3) @ (3, 2) -> (2, 2)

* (3, 2) @ (2, 3) -> (3, 3)

Note: "@" in Python is the symbol for matrix multiplication.

In [23]:
# Create tensors
X = torch.randn(size = (2,3))
Y = torch.randn(size = (3,4))

X.shape , Y.shape

(torch.Size([2, 3]), torch.Size([3, 4]))

Both the matrices are compatible for matrix multiplication as their inner dimensions are same

In [24]:
print(torch.matmul(X,Y))
print(torch.matmul(X,Y).shape)


tensor([[-1.4991,  1.3847, -2.9654, -1.7108],
        [ 0.4909, -0.3141, -2.5334, -0.9610]])
torch.Size([2, 4])


##### One of the most common errors in deep learning (shape errors)

Because much of deep learning is multiplying and performing operations on matrices and matrices have a strict rule about what shapes and sizes can be combined, one of the most common errors you'll run into in deep learning is shape mismatches.

In [25]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

We can make matrix multiplication work between tensor_A and tensor_B by making their inner dimensions match.

One of the ways to do this is with a transpose (switch the dimensions of a given tensor).

You can perform transposes in PyTorch using either:

`torch.transpose(input, dim0, dim1)` - where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.

`tensor.T` - where tensor is the desired tensor to transpose.

In [26]:
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [27]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


#### 4. Finding the min, max, mean, sum, etc (aggregation)

In [28]:
# create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [29]:
# Now perform some aggregation
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
print(f"Sum: {x.sum()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype

Minimum: 0
Maximum: 90
Sum: 450
Mean: 45.0


Note: You may find some methods such as `torch.mean()` require tensors to be in `torch.float32` (the most common) or another specific datatype, otherwise the operation will fail.

In [30]:
# We can also do above with torch 
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

#### 5. Positional Min/Max

You can also find the index of a tensor where the max or minimum occurs with `torch.argmax()` and `torch.argmin()` respectively.

In [31]:
print(f"Index where max value occurs: {x.argmax()}")  # x is the tensor that we have created above
print(f"Index where min value occurs: {x.argmin()}")

Index where max value occurs: 9
Index where min value occurs: 0


#### 6. Change tensor datatype

You can change the datatypes of tensors using `torch.Tensor.type(dtype=None)` where the `dtype` parameter is the datatype you'd like to use.

In [32]:
# create a tensor and check it's datatype
tensor = torch.arange(1,10,1.5)
tensor , tensor.dtype

(tensor([1.0000, 2.5000, 4.0000, 5.5000, 7.0000, 8.5000]), torch.float32)

In [33]:
# Create another tensor as before but change it dtype
tensor_float_16 = tensor.type(torch.float16)
tensor_float_16

tensor([1.0000, 2.5000, 4.0000, 5.5000, 7.0000, 8.5000], dtype=torch.float16)

#### 7. Reshaping, stacking, squeezing and unsqueezing

They all are used to reshape , change the dimensions without changing the values inside the tensor.

In [34]:
# create a tensor
x = torch.arange(1,10)
x , x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [35]:
# change the shape of the tensor
x_new = x.reshape(shape = (3,3))
x_new , x_new.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [36]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [37]:
# to stack one tensor on top of eachother
x_stacked =torch.stack([x,x,x],dim=1)    # default dimension is 0
x_stacked

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5],
        [6, 6, 6],
        [7, 7, 7],
        [8, 8, 8],
        [9, 9, 9]])

In [38]:
x.shape

torch.Size([9])

#### 7. Indexing (selecting data from tensors)

In [39]:
# create a tensor
x = torch.arange(1,10).reshape(1,3,3)
x , x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

 General form of the index `x[batch, row, column]`

In [55]:
# Select first batch of x
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [56]:
# select rows from the 1st batch
print(f"First row : {x[0,0]}")
print(f"second row : {x[0,1]}")
print(f"Third row : {x[0,2]}")

First row : tensor([1, 2, 3])
second row : tensor([4, 5, 6])
Third row : tensor([7, 8, 9])


In [59]:
# Slect a single element from a specific row from the the specific batch
print(f"First element of the first row of the first batch is : {x[0,0,0]}")
print(f"Second element of the second row of the first batch is : {x[0,1,1]}")

First element of the first row of the first batch is : 1
Second element of the second row of the first batch is : 5


The colon `:` operator

A colon means `select everything from this dimension`.

In [62]:
# select all batches row 1
print(x[:,1,:])
print(x[:,1,:].shape)

tensor([[4, 5, 6]])
torch.Size([1, 3])


In [65]:
# Select all rows , column 1
x[:,:,1]

tensor([[2, 5, 8]])

In [66]:
# select the first column
x[:,:,0]

tensor([[1, 4, 7]])