### PyTorch Fundamentals

In [2]:
## Import Pytorch and check it's version
import torch
print(f"The Current PyTorch version is :{torch.__version__}")

The Current PyTorch version is :2.11.0+cpu


#### 1. Creating Tensors

In [3]:
## 1.1 Scalar ( a single number)
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# let's print more about it
print(f"Scalar : {scalar}")
print(f"Dimension : {scalar.ndim}")
print(f"Shape : {scalar.shape}")
print(f"Device on which scalar is running : {scalar.device}")

Scalar : 7
Dimension : 0
Shape : torch.Size([])
Device on which scalar is running : cpu


In [5]:
# 1.2 Vector (a 1-D array of numbers)
vector = torch.tensor([1,2,3])

In [6]:
print(f"Vector : {vector}")
print(f"Dimension : {vector.ndim}")
print(f"Shape : {vector.shape}")  # (n,) n is number of elements
print(f"Device on which vector is running : {vector.device}")

Vector : tensor([1, 2, 3])
Dimension : 1
Shape : torch.Size([3])
Device on which vector is running : cpu


In [7]:
# 1.3 Matrix (a 2-D array of numbers)
MATRIX = torch.tensor([[1, 2 ,3],
                       [5, 6 , 7]
])

In [8]:
print(f"Matrix : {MATRIX}")
print(f"Dimension : {MATRIX.ndim}")
print(f"Shape : {MATRIX.shape}")  # (rows , columns)

Matrix : tensor([[1, 2, 3],
        [5, 6, 7]])
Dimension : 2
Shape : torch.Size([2, 3])


In [9]:
# 1.4 Tensor (a generalization of all to n dimensions)
TENSOR= torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

In [10]:
print(f"Tensor : {TENSOR}")
print(f"Dimension : {TENSOR.ndim}")
print(f"Shape : {TENSOR.shape}")

Tensor : tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Dimension : 3
Shape : torch.Size([2, 2, 2])


Things to remember:

A Tensor is a `genralization` of scalar , vector and matrix to `n` dimensions

* A Tensor of `0` dimension is a `Scalar`.
* A Tensor of `1` dimension is a `Vector`.
* A Tensor of `2` dimension is a `Matrix`.

Generally we called Tensor to a Tensor have more than `2` dimension.

Note:

* *`torch.Size` (or .shape) tells you how many elements exist along each dimension of a tensor.*
* For a tensor with shape [d0, d1, d2, ..., dn]:

     Number of values in the shape = number of dimensions of the tensor.

     Each value = size (length) of that specific dimension.
     
* Total number of elements = product of all shape values


In [11]:
# 1.5 Zero Tensor (having 0's as an  element)
zero_tensor = torch.zeros(size = (2,2))
print(f"Tensor : {zero_tensor}")
print(f"Dimension : {zero_tensor.ndim}")
print(f"Shape : {zero_tensor.shape}")

Tensor : tensor([[0., 0.],
        [0., 0.]])
Dimension : 2
Shape : torch.Size([2, 2])


In [12]:
# 1.6 Ones Tensor (having 1's as an element)
ones_tensor = torch.ones(size = (3,3))
print(f"Tensor : {ones_tensor}")
print(f"Dimension : {ones_tensor.ndim}")
print(f"Shape : {ones_tensor.shape}")

Tensor : tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
Dimension : 2
Shape : torch.Size([3, 3])


In [13]:
# 1.7 Range Tensor
range_tensor = torch.arange(start = 1.5,
                            step = 1,
                            end = 10.98)
range_tensor

tensor([ 1.5000,  2.5000,  3.5000,  4.5000,  5.5000,  6.5000,  7.5000,  8.5000,
         9.5000, 10.5000])

Note: In Python, you can use `range()` to create a range. However in PyTorch, `torch.range()` is deprecated and may show an error in the future.

In [15]:
# 1.8 Random tensor
random_tensor = torch.rand(size = (2,3))
random_tensor

tensor([[0.6588, 0.0774, 0.6472],
        [0.7810, 0.1138, 0.8862]])

`torch.rand()` Returns a tensor filled with random numbers from a uniform distribution on the interval [0,1).

The shape of the tensor is defined by the variable argument `size`.

Note:

In PyTorch, both `torch.rand()` and `torch.randn()` generate random tensors, but they differ in the distribution of the generated values.

`torch.rand()` Generates numbers uniformly between 0 and 1

`torch.randn()` Generates numbers from a standard normal distribution (mean = 0, std = 1).

In [20]:
random = torch.randn(size = (2,3))
random

tensor([[ 0.4441, -0.1254, -1.4539],
        [-1.1944, -0.0352, -1.5475]])

In [24]:
# Let's check it's mean and standard deviation (it will be nearly 0 and 1 not exact!)
mean = random.mean()
std = random.std()

print(f"Mean is {mean}")
print(f"Standard deviation is {std}")

Mean is -0.6520586013793945
Standard deviation is 0.8483466506004333
